server:
  port: 8080
  tomcat:
    url-encoding: utf-8

spring:
    mvc:
        view:
            prefix: /
            #suffix: .ftl
    #数据源配置
    datasource:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver

    redis:
      host: 127.0.0.1
      port: 6379
      database: 0




#    session:
#      store-type: none






mybatis:
#  type-aliases-package: com.example.demo.model
  mapper-locations: classpath*:mapper/*.xml


